source:[
  "Cakefile"
  "Nemfile"
  "config/nem"
  "src/signals"
  "src/std"
  "src/keys"
  "src/mixins"
  "src/module"
  "src/widgets"
  "src/container"
  "src/button"
  "src/textinput"
  "src/textarea"
  "src/checkbox"
  "src/radio"
  "src/radiogroup"
  "src/numeric-widget"
  "src/slider"
  "src/stepper"
  "src/filepicker"
  "src/menus"
  "src/selects"
  "src/calendar"
  "src/dates"
  "src/colorpicker"
  "src/jquery"
  "demos/builder"
  "demos/form"
  "test/test-signals"
  "test/test-std"
  "test/test-keys"
  "test/test-widgets"
  "test/test-container"
  "test/test-button"
  "test/test-textinput"
  "test/test-textarea"
  "test/test-checkbox"
  "test/test-radio"
  "test/test-radiogroup"
  "test/test-numeric-widget"
  "test/test-slider"
  "test/test-stepper"
  "test/test-filepicker"
  "test/test-menus"
  "test/test-selects"
  "test/test-calendar"
  "test/test-dates"
  "test/test-colorpicker"
  "test/test-jquery"
  "test/test-builder"
]
